version: '3.9'

services:
  apps:
    image: ardyantohermawan/node-starter:${TAG}
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    environment:
      PORT: 3000