version: '3.1'

services:
  mongo:
    image: mongo:3.6.17-xenial
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: company
    volumes:
      - ./mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  # apps:
  #   build: .
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   links:
  #     - mongo:mongo
  #   environment:
  #     MONGODB_DBNAME: company
  #     MONGODB_URL: mongodb://administrator:administrator@mongo:27017/company
  #     MONGODB_COLLECTION: employees
  #     PORT: 3000
      